'use strict';
const $=id=>document.getElementById(id), token=document.querySelector('meta[name=session-token]').content;
let state=null, messageKey='', selectedSource=null, memoryMode='history', pageOffset=0, nextOffset=null, polling=false;
async function api(path,body){const opts={headers:{'X-SwitchLab-Token':token}};if(body!==undefined){opts.method='POST';opts.headers['Content-Type']='application/json';opts.body=JSON.stringify(body);}const r=await fetch(path,opts);const v=await r.json();if(!r.ok)throw Error(v.error||'请求失败');return v;}
function toast(text){$('toast').textContent=text;$('toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').hidden=true,6500);}
async function perform(fn){try{return await fn();}catch(e){toast(e.message);return null;}}
function button(text,fn,cls=''){const b=document.createElement('button');b.type='button';b.textContent=text;if(cls)b.className=cls;b.addEventListener('click',()=>perform(fn));return b;}
function node(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
function show(id){if(!$(id).open)$(id).showModal();}document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());
const statusNames={accepted:'已采纳',proposed:'待商量',needs_clarification:'时间待澄清',needs_review:'需要重新商量',in_progress:'进行中',completed:'已完成',cancelled:'已取消'};
function dateLabel(c){if(c.due_at===null)return c.when?'时间尚未明确：'+c.when:'时间未定';return (c.due_display||new Date(c.due_at*1000).toISOString()).replace('T',' ')+'（原话：'+c.when+'）';}
function renderMessages(){const msgs=state.messages,key=JSON.stringify(msgs);if(key===messageKey)return;messageKey=key;const box=$('messages'),nearBottom=box.scrollTop+box.clientHeight>=box.scrollHeight-100;box.replaceChildren();if(!msgs.length){const e=node('div','今天想一起做什么？','empty');e.append(node('p','过去的经历留在本地，当前工作空间只读需要的部分。'));box.append(e);return;}
for(const m of msgs){const article=node('article',undefined,'message '+(m.actor==='user'?'user':'agent'));article.append(node('div',m.actor==='user'?'你':state.name,'message-head'));article.append(node('div',m.text,'bubble'));const actions=node('div',undefined,'receipt');actions.append(button('来源',()=>openSource(m.id),'technical'));if(m.actor==='user'&&!m.responded&&m.at!==null)actions.append(button('重新处理',async()=>{await api('/api/resume-turn',{source:m.id});await refresh();}));if(m.source.contact){actions.append(button('现在方便',async()=>{await api('/api/feedback',{contact:m.source.contact,outcome:'available',explanation:'这次联系时我方便回复。'});await refresh();}));actions.append(button('这次不方便',async()=>{await api('/api/feedback',{contact:m.source.contact,outcome:'busy',explanation:'这次联系时我正忙，不方便回复。'});await refresh();}));}article.append(actions);box.append(article);}if(nearBottom||msgs.length<5)box.scrollTop=box.scrollHeight;}
function commitmentCard(c){const box=node('div',undefined,'commit-card');box.append(node('div',c.title,'commit-title'));box.append(node('div',(statusNames[c.status]||c.status)+' · v'+c.revision,'commit-state'));box.append(node('div',dateLabel(c),'muted'));const act=node('div',undefined,'commit-actions');act.append(button('来源',()=>openSource(c.source)));act.append(button('变更历史',async()=>{const r=await api('/api/versions?id='+encodeURIComponent(c.id));$('contextView').hidden=false;$('contextView').textContent=JSON.stringify(r,null,2);show('memoryDialog');}));if(!['completed','cancelled'].includes(c.status)){act.append(button('改约',()=>editCommitment(c)));act.append(button('完成',()=>closeCommitment(c,'complete')));act.append(button('取消',()=>closeCommitment(c,'cancel')));}box.append(act);return box;}
function render(){if(!state)return;const rt=state.runtime;$('personName').textContent='和'+state.name+'一起';$('personId').textContent='个体 '+state.person_id.slice(0,10);$('clock').textContent=state.time.replace('T',' ');$('presence').textContent=rt.busy?'正在处理':rt.background?'后台已开启':'执行已暂停';$('presenceDot').className=rt.background?'active':'';$('status').textContent=rt.status;$('runtimeError').hidden=!rt.error;$('runtimeError').textContent=rt.error;$('backgroundButton').textContent=rt.background?'后台处理已开启':'允许后台处理约定';$('backgroundButton').disabled=rt.background;$('setupNotice').hidden=rt.options.language_mode==='api';$('setupNotice').textContent=rt.options.language_mode==='manual'?'当前使用手动模型交换。原始经历仍在本地保存；每个语言步骤需要你传递请求。':'未连接语言模型：原话会保存，本地报告不能代替对口头约定的自然理解。';$('manualButton').hidden=!rt.manual_request;$('runtimeSummary').textContent='事件序号 '+state.events+' · 累计模型请求 '+rt.calls+' / 已授权 '+rt.call_ceiling;$('learningSummary').textContent='联系结果：'+state.learning.unique_outcomes+' 个独特样本；更新 '+state.learning.updates+' 次（实验逻辑预测器）；默认联系预测用独特结果计数。'+(state.learning.enabled?'学习开启。':'学习冻结。')+' 这是局部联系时机预测，不是好感或意识评分。';$('freezeButton').textContent=state.learning.enabled?'冻结学习':'启用学习';renderMessages();const c=$('commitments');c.replaceChildren();if(!state.commitments.items.length)c.append(node('p','还没有未完成的约定。你可以自然地提出一件以后想一起做的事。','muted'));else state.commitments.items.slice(0,8).forEach(x=>c.append(commitmentCard(x)));if(state.commitments.total>8)c.append(node('p','还有 '+(state.commitments.total-8)+' 项，查看全部可分页读取。','muted'));if($('worldDialog').open)renderWorld();}
async function refresh(){if(polling)return;polling=true;try{state=await api('/api/state');render();}catch(e){$('status').textContent='连接本地程序失败：'+e.message;}finally{polling=false;}}
$('chatForm').onsubmit=e=>{e.preventDefault();perform(async()=>{const text=$('messageInput').value;if(!text.trim())return;await api('/api/chat',{text});$('messageInput').value='';await refresh();$('messages').scrollTop=$('messages').scrollHeight;});};$('messageInput').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();$('chatForm').requestSubmit();}};
$('backgroundButton').onclick=()=>perform(async()=>{if(!confirm('允许程序在运行期间检查到期约定，并在本聊天中主动联系。连接模型时可能计费，受已授权请求上限控制。继续？'))return;await api('/api/background',{});await refresh();});$('pauseButton').onclick=()=>perform(async()=>{await api('/api/pause',{});await refresh();});
function openConfig(){if(!state)return;const p=state.runtime.provider;$('languageMode').value=state.runtime.options.language_mode;$('baseUrl').value=p.base_url;$('modelId').value=p.model;$('apiKey').value='';$('clearKey').checked=false;$('networkConsent').checked=p.network_consent;$('jsonMode').checked=p.json_mode;$('outputTokens').value=p.max_output_tokens;$('timeout').value=p.timeout;$('maxCalls').value=p.max_calls;$('tokenParameter').value=p.token_parameter;$('timezone').value=state.memory_settings.timezone==='UTC'?(Intl.DateTimeFormat().resolvedOptions().timeZone||'UTC'):state.memory_settings.timezone;$('memoryBudget').value=state.memory_settings.memory_budget_bytes;$('connectionResult').textContent='';show('configDialog');}
$('configButton').onclick=openConfig;$('timezoneButton').onclick=openConfig;
$('configForm').onsubmit=e=>{e.preventDefault();perform(async()=>{const mode=$('languageMode').value,config={mode:mode==='api'?'api':'manual',base_url:$('baseUrl').value,model:$('modelId').value,json_mode:$('jsonMode').checked,max_output_tokens:Number($('outputTokens').value),timeout:Number($('timeout').value),max_calls:Number($('maxCalls').value),token_parameter:$('tokenParameter').value,network_consent:$('networkConsent').checked};await api('/api/config',{config,key:$('apiKey').value,clear_key:$('clearKey').checked});await api('/api/memory-settings',{timezone:$('timezone').value,memory_budget_bytes:Number($('memoryBudget').value)});await api('/api/options',{language_mode:mode});$('apiKey').value='';$('configDialog').close();toast('设置已保存，执行保持暂停。');await refresh();});};
$('connectionCheck').onclick=()=>perform(async()=>{if(!confirm('按已保存的连接发送一次最小测试，可能计费。继续？'))return;$('connectionResult').textContent='请求中……';const r=await api('/api/check',{});$('connectionResult').textContent=JSON.stringify(r,null,2);await refresh();});$('grantButton').onclick=()=>perform(async()=>{const raw=prompt('追加多少次模型请求？每次1..500；不会清空长期经历。','48');if(raw===null)return;const n=Number(raw);if(!confirm('允许再使用 '+n+' 次请求，可能产生费用。确认？'))return;const r=await api('/api/grant',{count:n});toast('当前累计请求上限 '+r.ceiling);await refresh();});
async function loadMemory(mode='history',offset=0){memoryMode=mode;pageOffset=offset;$('contextView').hidden=true;let p;if(mode==='search')p='/api/search?q='+encodeURIComponent($('searchInput').value)+'&offset='+offset;else if(mode==='commitments')p='/api/commitments?closed=1&offset='+offset;else p='/api/history?offset='+offset;const r=await api(p),box=$('memoryResults');box.replaceChildren(node('p','本页 '+r.items.length+' / 共 '+r.total+' 项；'+(r.complete?'已到末页':'后续还有记录'),'muted'));for(const x of r.items){if(mode==='commitments')box.append(commitmentCard(x));else{const row=node('div',undefined,'memory-row');row.append(node('small',x.id+' · '+x.actor+' · '+x.namespace+(x.at===null?' · 原始日期未知':'')));row.append(node('div',x.text.slice(0,500),'body'));row.append(button('读完整来源',()=>openSource(x.id)));box.append(row);}}nextOffset=r.next_offset;$('nextPageButton').hidden=r.complete;show('memoryDialog');}
$('memoryButton').onclick=()=>perform(()=>loadMemory());$('historyButton').onclick=()=>perform(()=>loadMemory());$('listCommitmentsButton').onclick=()=>perform(()=>loadMemory('commitments'));$('allCommitmentsButton').onclick=()=>perform(()=>loadMemory('commitments'));$('searchForm').onsubmit=e=>{e.preventDefault();perform(()=>loadMemory('search'));};$('nextPageButton').onclick=()=>perform(()=>loadMemory(memoryMode,nextOffset));$('contextButton').onclick=()=>perform(async()=>{$('contextView').textContent=JSON.stringify(await api('/api/context'),null,2);$('contextView').hidden=false;});$('replayButton').onclick=()=>perform(async()=>{const r=await api('/api/replay',{});toast('实验预测器梯度步数 '+r.gradient_steps+'；新增证据 '+r.new_external_evidence+'。默认计数策略不因重放增加证据。');await refresh();});$('freezeButton').onclick=()=>perform(async()=>{await api('/api/memory-settings',{learning:!state.learning.enabled});await refresh();});$('reindexButton').onclick=()=>perform(async()=>{await api('/api/reindex',{});toast('索引从保留的原文重建，没有生成新经历。');});
async function openSource(id){selectedSource=await api('/api/source?id='+encodeURIComponent(id));$('sourceMeta').textContent=selectedSource.id+' · '+selectedSource.actor+' · '+selectedSource.namespace+' · '+(selectedSource.at===null?'原始真实日期未知':new Date(selectedSource.at*1000).toLocaleString());$('sourceText').textContent=selectedSource.text+'\n\n── 来源元数据 ──\n'+JSON.stringify(selectedSource.source,null,2);$('resumeSourceButton').hidden=selectedSource.actor!=='user'||selectedSource.at===null;show('sourceDialog');}
$('resumeSourceButton').onclick=()=>perform(async()=>{await api('/api/resume-turn',{source:selectedSource.id});$('sourceDialog').close();$('memoryDialog').close();await refresh();});$('forgetSourceButton').onclick=()=>perform(async()=>{if(!confirm('删除此原文和依赖它的内容，并清除学习器及本程序管理的备份？涉及旧导入或探索来源时，相应模拟状态将重置。外部导出需要你自行处理。'))return;const r=await api('/api/forget',{source_ids:[selectedSource.id],confirmed:true});$('sourceDialog').close();toast('删除了 '+r.removed_observations+' 条来源/派生表达。');messageKey='';await refresh();if($('memoryDialog').open)await loadMemory();});
function editCommitment(c=null){$('commitmentId').value=c?.id||'';$('commitmentRevision').value=c?.revision||'';$('commitmentTitle').value=c?.title||'';$('commitmentCategory').value=c?.category||'activity';$('commitmentQuote').value='';$('commitmentWhen').value='';$('commitmentHeading').textContent=c?'修订同一个约定':'明确记录约定';show('commitmentDialog');}
$('addCommitmentButton').onclick=()=>editCommitment();$('commitmentForm').onsubmit=e=>{e.preventDefault();perform(async()=>{const id=$('commitmentId').value,p={op:id?'revise':'create',title:$('commitmentTitle').value,category:$('commitmentCategory').value,quote:$('commitmentQuote').value,when:$('commitmentWhen').value,accept:true};if(id){p.id=id;p.expected_revision=Number($('commitmentRevision').value);}await api('/api/commitment',p);$('commitmentDialog').close();await refresh();});};
async function closeCommitment(c,op){const q=prompt(op==='cancel'?'请说明这次取消：':'请说明实际完成的情况：',(op==='cancel'?'取消这次':'我们已经完成了')+c.title);if(q===null)return;await api('/api/commitment',{id:c.id,expected_revision:c.revision,op,quote:q});await refresh();}
$('manualButton').onclick=()=>{const r=state.runtime.manual_request;if(!r)return;$('manualPhase').textContent='当前阶段：'+r.phase+'。模型输出作为外部输入记录。';$('manualPrompt').value=r.prompt;$('manualResponse').value='';show('manualDialog');};$('copyPromptButton').onclick=()=>perform(async()=>{await navigator.clipboard.writeText($('manualPrompt').value);toast('请求已复制');});$('submitManualButton').onclick=()=>perform(async()=>{const r=state.runtime.manual_request;if(!r)throw Error('请求已过期');await api('/api/manual',{request_id:r.id,text:$('manualResponse').value});$('manualDialog').close();await refresh();});
$('backupButton').onclick=()=>perform(async()=>{const r=await api('/api/backup',{});toast('已建立备份：'+r.file);});$('exportButton').onclick=()=>perform(async()=>{const r=await fetch('/api/export',{headers:{'X-SwitchLab-Token':token}});if(!r.ok)throw Error('导出失败');const url=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=url;a.download='SharedField_v06_checkpoint.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);});$('importButton').onclick=()=>$('importFile').click();$('importFile').onchange=()=>perform(async()=>{const f=$('importFile').files[0];if(!f)return;if(f.size>128*1024*1024)throw Error('导入超过128MiB，请使用命令行和备份方案');if(!confirm('导入前会备份当前经历，接续后暂停。旧文件可能包含你曾主动删除的资料；确认是希望恢复的副本？'))return;const cp=JSON.parse(await f.text());toast('正在用对应代码验证，可能需要等待……');await api('/api/import',{checkpoint:cp,archive_current:true});messageKey='';await refresh();toast('接续完成，执行暂停。');$('importFile').value='';});
function renderWorld(){const w=state.world.world,obs=state.world;const map=$('worldMap');map.replaceChildren();$('worldSummary').textContent='物理步骤 '+w.tick+' · '+state.world.cognition.state_words;const rooms=w.agent?.visible_rooms||w.visible_rooms||w.rooms||[];for(const r of rooms){const el=node('div',undefined,'room');el.append(node('strong',r.name||String(r.id)));el.append(node('span',r.kind||''));el.append(button('我去这里',async()=>{await api('/api/world',{kind:'player_action',payload:{action:{kind:'move',target:r.id}}});await refresh();}));map.append(el);}if(!rooms.length)map.append(node('p','当前位置与路线请在状态详情中查看；可先调查或让她行动。','muted'));}
$('worldButton').onclick=()=>{show('worldDialog');renderWorld();};for(const [id,kind,payload] of [['worldSurvey','player_action',{action:{kind:'survey'}}],['worldRest','player_action',{action:{kind:'rest'}}],['worldTogether','activity',{mode:'together'}],['worldWait','activity',{mode:'wait'}],['worldResume','activity',{mode:'resume'}],['worldIndependent','activity',{mode:'independent'}]])$(id).onclick=()=>perform(async()=>{await api('/api/world',{kind,payload});await refresh();});$('worldStep').onclick=()=>perform(async()=>{await api('/api/advance',{});await refresh();});$('worldAuto').onclick=()=>perform(async()=>{await api('/api/auto',{steps:8});await refresh();});$('newExpedition').onclick=()=>perform(async()=>{if(!confirm('更换模拟地图，长期个人记忆和约定保留。继续？'))return;await api('/api/world',{kind:'new_expedition',payload:{}});await refresh();});
refresh();setInterval(refresh,1400);
