import assert from 'node:assert/strict';
import {placeNextBlock} from './placement.mjs';
const mc={getBlockId:n=>n==='unknown'?null:1};
let stock=4,worldBlocks=new Map(),target=0,calls=[];
const pos=x=>({x,y:2,z:3});
const bot={inventory:{items:()=>[{name:'oak_planks',count:stock}]},blockAt:p=>({name:worldBlocks.get(p.x)||'air'})};
const world={getNearestFreeSpace:()=>pos(++target)};
const skills={async placeBlock(_bot,block,x,y,z,side,dontCheat){calls.push({x,y,z,side,dontCheat});worldBlocks.set(x,block);stock--}};
const first=await placeNextBlock(bot,mc,world,skills,'oak_planks');
const second=await placeNextBlock(bot,mc,world,skills,'oak_planks');
assert.equal(first.verified,true);assert.equal(second.verified,true);
assert.notDeepEqual(first.position,second.position);assert.equal(stock,2);
assert.equal(first.placement.before_block,'air');assert.equal(first.placement.after_block,'oak_planks');
assert.equal(first.placement.consumed,1);assert.ok(calls.every(c=>c.dontCheat===true));
const occupied=await placeNextBlock(bot,mc,{getNearestFreeSpace:()=>pos(1)},skills,'oak_planks');
assert.equal(occupied.status,'placement_target_not_empty');assert.equal(calls.length,2);
const noDelta=await placeNextBlock(bot,mc,world,{async placeBlock(_b,block,x){worldBlocks.set(x,block)}},'oak_planks');
assert.equal(noDelta.verified,false);assert.equal(noDelta.placement.consumed,0);
stock=0;
assert.equal((await placeNextBlock(bot,mc,world,skills,'oak_planks')).status,'placement_material_missing');
assert.equal((await placeNextBlock(bot,mc,world,skills,'unknown')).status,'unknown_block');
console.log('14 placement checks passed: distinct world changes, inventory consumption, occupied target, no progress, missing material, unknown block');
